### ISSUE TITLE
Status tracker or estimated timelines

### ISSUE THREAD

**Issue by vsr4493** [cfredric/chrome-storage-access-api#1]
Hello! Is there a way to track the status for this API or any estimated timelines for the same?

I was looking around and https://chromestatus.com/feature/5612590694662144 seems out of date w.r.t shipping dates.

On the bug tracker going by https://bugs.chromium.org/p/chromium/issues/detail?id=989663#c32, looks like this will be the only way to get storage access unless the site is part of a first party set.

**Comment by cfredric** [comment]
Hi @vsr4493! We haven't announced official shipping timeline plans yet, but we're expecting to have more info on that soon.

When those details are ready, we'll post them to [blink-dev@chromium.org](https://groups.google.com/u/1/a/chromium.org/g/blink-dev), in an "Intent to Ship" thread. You can keep an eye on [blink-dev@chromium.org](https://groups.google.com/u/1/a/chromium.org/g/blink-dev)) to be among the first to know! I've also added an "announcements" section to the README in this repo, and I'll add relevant links there when we have more info to share.

I'll close this issue since hopefully that (sort of) answers your question, but feel free to reopen if you have more questions.
