### ISSUE TITLE
Request Storage Access page Security model 

### ISSUE THREAD

**Issue by jagadeeshaby** [cfredric/chrome-storage-access-api#5]
Customers are allowed (frame ancestor)  to use our SASS application embedded in their website after the successful login ( SSO integration), with the 3p cookie deprecation our plan is to make use of RSA and allow access to login cookies, to make this happen i see that chrome expects a  explicit interaction with the embedded page ( example click ).  what's the recommended approach to build such embedded page where customer could click and request access? 

At the moment , it seems like i need to have a non logged in page embedded to conditionally show the button to grant access or take them to application. i presume this comes with a potential click jacking risk as we do not have the allow listed origins to populate as customer hasn't logged in yet. 

Any suggestions here?

**Comment by cfredric** [comment]
Hi @jagadeeshaby,

I'd like to understand more about your concerns with the Storage Access API's design in general, and with Chrome's behavior specifically. Can you give any more detail about what difficulties you're anticipating?

> what's the recommended approach to build such embedded page where customer could click and request access?

I don't know that Chrome has formal recommendations for this, but if I were a web developer, I would try to explain to the user why they need to click the button and allow access in order to accomplish what they're trying to do, and make sure they know what behavior to expect once they click the button on your site. This could look pretty different depending on your site and its intended functionality, and your ability to explain that functionality to your users.

> At the moment , it seems like i need to have a non logged in page embedded to conditionally show the button to grant access or take them to application.

That's correct; if third-party cookies are blocked, an embedded cross-site iframe cannot access unpartitioned cookies until it indicates its desire to access them by calling `document.requestStorageAccess()`. (Even then, access might still be blocked if the user denies the request.) That method requires a user gesture if the user has not granted permission yet; but if the user has already granted permission, then no user gesture is required (in Chrome). (Note that other browsers may impose different constraints; the spec does not *prohibit* requiring a gesture in other situations.)

> i presume this comes with a potential click jacking risk as we do not have the allow listed origins to populate as customer hasn't logged in yet.

Interesting. So you are concerned that your site may be embedded in a malicious site that may try to steal the user-gesture when users try to click in your iframe to allow unpartitioned cookie access. And IIUC you do not know beforehand on which origins you expect to be embedded, so you cannot use `Content-Security-Policy: frame-ancestors ...` as protection. Is that correct?

If I'm understanding correctly, the fear is that a malicious page would not be able to get a user gesture on its own (so wouldn't be able to call [powerful APIs](https://www.w3.org/TR/design-principles/#require-user-activation)), but if it embedded your site, your site would convince the user to interact (e.g. click a button), and then the malicious page has the opportunity to intercept the gesture and do something nefarious with it.

If I've got that right so far, the remedy that comes to my mind is to augment the Storage Access API spec in some way that allows a third-party site to request `storage-access` permission under a given top-level site, while it itself is in a top-level context. That way, your site does not need to convince users to click while it's in an embedded context, and therefore the malicious site has no opportunity to intercept a click (since the click occurs when your site is in a top-level context). This seems like what e.g. https://github.com/bvandersloot-mozilla/top-level-storage-access is attempting to accomplish, albeit with different motivations; please take a look at that proposal and see if that would address your concerns.

**Comment by jagadeeshaby** [comment]
Thank you for the detailed explanation.  

We going ahead with the RSA and we believe this page meets all the best practices to avoid any possible exploits
